language: ruby
cache: bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  matrix:
    #- BUILD=buildPDF.sh
    - BUILD=buildPages.sh
    - BUILD=buildBluemix.sh
    - BUILD=buildElastic.sh
script: ./build/$BUILD
branches:
  only:
  - master
  - translation-staging
rvm:
- 2.3.1 # version of `ruby'
git:
  depth: 9999999
notifications:
  slack:
    rooms:
      secure: LL9BQGH/n8hSdXPiLfZZna2zHAvBe1NfQRdZtWglKQ5z/K8w4hH5yV9cHxZOHblkznAi7HotEB5vmTp4Pizm5aCPgY4R/HM95Y57fOH1joKIGv1rw433JsFKR7GdFyKfQuthjW9q2bvN5T0LQp6V1GJfQ3PiYDX+lFbCY9Rr/aA=
    on_success: never
  email:
      recipients:
        - sreelathas@in.ibm.com
      on_success: always
      on_failure: always
